# FlexLM License Servers (Triad)
export FS1=n1lflexp02.corp.cat.com
export FS2=aclflexp01.acric.cat.com
export FS3=mtlflexp03.corp.cat.com

# ABAQUS
FV_ABAQUS=abaquslm
FP_ABAQUS=37000
FL_ABAQUS=$FP_ABAQUS@$FS1:$FP_ABAQUS@$FS2:$FP_ABAQUS@$FS3
PATH_ABAQUS=

# FLUENT
FV_FLUENT=fluentlm
FP_FLUENT=7241
FL_FLUENT=$FP_FLUENT@$FS1:$FP_FLUENT@$FS2:$FP_FLUENT$FS3
PATH_FLUENT=

# StarCCM+, StarCD
FV_STARCD=cdlmd
FP_STARCD=25199
FL_STARCD=$FP_STARCD@$FS1:$FP_STARCD@$FS2:$FP_STARCD$FS3
PATH_STARCD=

# ANSYS
FV_ANSYS=ansyslmd
FP_ANSYS=25009
FL_ANSYS=$FP_ANSYS@$FS1:$FP_ANSYS@$FS2:$FP_ANSYS$FS3
PATH_ANSYS=

# NASTRAN
#FP_NASTRAN=
#FL_NASTRAN=$FP_NASTRAN@$FS1:$FP_NASTRAN@$FS2:$FP_NASTRAN$FS3
#PATH_NASTRAN=

# RadTherm
FV_RADTHERM=taitherm
FP_RADTHERM=27012
FL_RADTHERM=$FP_RADTHERM@$FS1:$FP_RADTHERM@$FS2:$FP_RADTHERM$FS3
PATH_RADTHERM=

# ANSOFT
FV_ANSOFT=ansoftd
FP_ANSOFT=25200
FL_ANSOFT=$FP_ANSOFT@$FS1:$FP_ANSOFT@$FS2:$FP_ANSOFT$FS3
PATH_ANSOFT=

# Isight (SIMULIA)
FV_ISIGHT=engswd
FP_ISIGHT=27013
FL_ISIGHT=$FP_ISIGHT@$FS1:$FP_ISIGHT@$FS2:$FP_ISIGHT$FS3
PATH_ISIGHT=

# Caterpillar
## PES
FV_CAT_PES=catlmd
FP_CAT_PES=25060
FL_CAT_PES=$FP_CAT_PES@$FS1:$FP_CAT_PES@$FS2:$FP_CAT_PES$FS3
PATH_CAT_PES=

# FlexLM License File
LM_LICENSE_FILE=\
$FL_ABAQUS:\
$FL_FLUENT:\
$FL_STARCD:\
$FL_ANSYS:\
$FL_RADTHERM:\
$FL_ANSOFT:\
$FL_ISIGHT:\
$FL_CAT_PES:\
$LM_LICENSE_FILE

export LM_LICENSE_FILE

# Executable Search Path
PATH=$PATH:\
$PATH_ABAQUS:\
$PATH_FLUENT:\
$PATH_STARCD:\
$PATH_ANSYS:\
$PATH_RADTHERM:\
$PATH_ANSOFT:\
$PATH_ISIGHT:\
$PATH_CAT_PES:\
$HOME/bin

export PATH

if [[ ! -f $HOME/.flexlmrc ]]; then
  touch $HOME/.flexlmrc
fi

